<?
// Do not edit this file
// Copyright (C) Scott Atkins 2002 <atkinssc@engr.orst.edu>
// This is protected by GPL, see the README

$fp = fopen("http://" . $server . "/".$file, "r");
array_shift($http_response_header);
foreach($http_response_header as $h) header($h);
//foreach($http_response_header as $h) echo($h . "<BR>");
if($http_response_header[3] != "Content-Type: text/html"){
if($http_response_header[7] == "Content-Type: audio/mpeg" || $http_response_header[7] == "Content-Type: application/octet-stream"){
header("Content-Disposition: attachment; filename=" . $file);
}
fpassthru($fp);
die();
}
fclose($fp);

function redirect($start,$D,$a,$fileDir,$name)
{
	$start2 = stripslashes($start);
	foreach($D as $delim){
		if(eregi($start . $delim,$a) && ($delim == "" ? eregi($start . "[a-z,A-Z,/,0-9]",$a) : 1)){
			$a = eregi_replace($start . $delim . "/",$start2 . $delim . $name . "/test.php?file=",$a);
			$a = eregi_replace($start . $delim . "http://",$start2 . '\a' . "http://",$a);
			$a = eregi_replace($start . $delim ,$start2 . $delim . $name . "/test.php?file=" . $fileDir ,$a);
			$a = eregi_replace($start . '[\]a',$start2 . $delim, $a);
		}
	}
	return $a;
}
$fileDir = eregi_replace("[^/]*$","",$file);
$a = join(file("http://" . $server . "/".$file),'');

$delim[]='"';
$delim[]="'";
$delim[]="";

$a = redirect("src=",$delim,$a,$fileDir,$name);
$a = redirect("background=",$delim,$a,$fileDir,$name);
$a = redirect("href=",$delim,$a,$fileDir,$name);
$a = redirect("url\(",$delim,$a,$fileDir,$name);


echo $a;
?>
